############# French navigation ##############
# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "FAQ"
url = "faq/"
weight = 3

[[main]]
name = "Pricing"
url = "pricing/"
weight = 4

[[main]]
name = "Blog"
url = "blog/"
weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 6

[[main]]
name = "Legal"
weight = 7
hasChildren = true
  
  [[main]]
  parent = "Legal"
  name = "Testimonials"
  url = "testimonial/"
  
  [[main]]
  name = "Terms & Conditions"
  url = "terms-conditions/"
  parent = "Legal"

  [[main]]
  name = "Imprint"
  url = "imprint/"
  parent = "Legal"

  [[main]]
  name = "Privacy Policy"
  url = "privacy-policy/"
  parent = "Legal"

# Footer menu
[[footer]]
name = "Faq"
url = "faq/"
weight = 1

[[footer]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3