############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""      # don't use a slash for home url
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Pricing"
url = "pricing/"
weight = 3

[[main]]
name = "FAQ"
url = "pricing/#faq"
weight = 4

[[main]]
name = "Pages"
url = "blog/"
weight = 5
hasChildren = true

[[main]]
name = "Privacy Policy"
url = "privacy-policy/"
parent = "Pages"

[[main]]
name = "Contact"
url = "contact/"
weight = 7

[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Pricing"
url = "pricing/"
weight = 10

[[footer]]
name = "Blog"
url = "blog/"
weight = 20


[[footer]]
name = "Contact"
url = "contact/"
weight = 40

[[footer_bottom]]
name = "Privacy Policy"
url = "#"
weight = 1

[[footer_bottom]]
name = "Terms of Use"
url = "#"
weight = 10

[[footer_bottom]]
name = "Legal"
url = "#"
weight = 30

[[footer_bottom]]
name = "Site Map"
url = "#"
weight = 40