############# French navigation ##############
# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Über uns"
url = "about_myopiagraph/"
weight = 1

[[main]]
name = "Kontakt"
url = "contact/"
weight = 6

[[main]]
name = "Rechtliches"
weight = 7
hasChildren = true

  
  [[main]]
  name = "AGB"
  url = "terms-conditions/"
  parent = "Rechtliches"

  [[main]]
  name = "Impressum"
  url = "imprint/"
  parent = "Rechtliches"

  [[main]]
  name = "Datenschutz"
  url = "privacy-policy/"
  parent = "Rechtliches"

# Footer menu


[[footer]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3